cat_empresas_homepage:
    path:     /catempresas
    defaults: { _controller: CatEmpresasBundle:Default:catempresas }

cat_empresas_insertarEmpresa:
    path:     /insertarEmpresa
    defaults: { _controller: CatEmpresasBundle:Default:insertarEmpresa }

