catusuarios_homepage:
    path:     /catusuarios
    defaults: { _controller: catusuariosBundle:Default:catusuarios }

catusuario_insertarUsuario:
    path:     /insertarUsuario
    defaults: { _controller: catusuariosBundle:Default:insertarUsuario }

catusuario_eliminarUsuario:
    path:     /eliminarUsuario
    defaults: { _controller: catusuariosBundle:Default:eliminarUsuario }