login_homepage:
    path:     /login
    defaults: { _controller: loginBundle:Default:login }

login_insertarUsuario:
    path:     /insertarUsuario
    defaults: { _controller: catusuariosBundle:Default:insertarUsuario }

login_admin:
    path:     /admin
    defaults: { _controller: loginBundle:Default:admin }

